export const YOUTUBE_CHANNELS = [
  {
    id: 'whiteswantvonline',
    channelId: 'UCIy9yPSg_Jn1MknCBDnoC0w',
    title: 'Whiteswan TV News Official',
    titleMl: 'വൈറ്റ്സ്വാൻ ടിവി ന്യൂസ് ഒഫീഷ്യൽ',
    handle: '@whiteswantvonline',
    url: 'https://www.youtube.com/@whiteswantvonline',
    description: 'Malayalam Top Online News Media & Live Updates',
    badge: 'OFFICIAL',
    color: '#E50914',
    icon: 'logo-youtube',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=200&auto=format&fit=crop&q=80',
    tag: 'Main Channel',
  },
  {
    id: 'Whiteswanexclusive',
    channelId: 'UCwRdN_ltIm1tdZ-_gG7xTXQ',
    title: 'Whiteswan Exclusive',
    titleMl: 'വൈറ്റ്സ്വാൻ എക്സ്ക്ലൂസീവ്',
    handle: '@Whiteswanexclusive',
    url: 'https://www.youtube.com/@Whiteswanexclusive',
    description: 'Special investigative reports, sting operations and exclusive interviews',
    badge: 'EXCLUSIVE',
    color: '#D97706',
    icon: 'star',
    image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?w=200&auto=format&fit=crop&q=80',
    tag: 'Special Reports',
  },
  {
    id: 'whiteswaninside',
    channelId: 'UCB7xRNgLpatCKdu5CFYgTjA',
    title: 'Whiteswan Inside',
    titleMl: 'വൈറ്റ്സ്വാൻ ഇൻസൈഡ്',
    handle: '@whiteswaninside',
    url: 'https://www.youtube.com/@whiteswaninside',
    description: 'Behind the scenes, feature stories, cultural specials and deep dives',
    badge: 'INSIDE',
    color: '#7C3AED',
    icon: 'sparkles',
    image: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=200&auto=format&fit=crop&q=80',
    tag: 'Features & BTS',
  },
  {
    id: 'whiteswanhindi',
    channelId: 'UCWef-wcf1uC4aFT2jaOTMiw',
    title: 'Whiteswan Hindi',
    titleMl: 'വൈറ്റ്സ്വാൻ ഹിന്ദി',
    handle: '@whiteswanhindi',
    url: 'https://www.youtube.com/@whiteswanhindi',
    description: 'National and international news broadcasts and special updates in Hindi',
    badge: 'HINDI',
    color: '#EA580C',
    icon: 'globe-outline',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=200&auto=format&fit=crop&q=80',
    tag: 'National News',
  },
];

export const FACEBOOK_PAGES = [
  {
    id: 'fb_whiteswantvnews_official',
    title: 'Whiteswan TV News Official',
    titleMl: 'വൈറ്റ്സ്വാൻ ടിവി ന്യൂസ് ഒഫീഷ്യൽ',
    handle: '@WHITESWANTVNEWS',
    url: 'https://www.facebook.com/WHITESWANTVNEWS/',
    description: 'Official verified Facebook page for breaking news, live coverage and special reports',
    badge: 'OFFICIAL',
    color: '#1877F2',
    icon: 'logo-facebook',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&auto=format&fit=crop&q=80',
    tag: 'Official Page',
  },
  {
    id: 'fb_whiteswantvmalayalam',
    title: 'Whiteswan TV Malayalam',
    titleMl: 'വൈറ്റ്സ്വാൻ ടിവി മലയാളം',
    handle: '@whiteswantv',
    url: 'https://www.facebook.com/whiteswantv/',
    description: 'Official Malayalam Facebook page for real-time news alerts, debate videos and live broadcasts',
    badge: 'MALAYALAM',
    color: '#1877F2',
    icon: 'logo-facebook',
    image: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200&auto=format&fit=crop&q=80',
    tag: 'Malayalam Page',
  },
  {
    id: 'fb_whiteswantvhindi',
    title: 'Whiteswan TV Hindi',
    titleMl: 'വൈറ്റ്സ്വാൻ ടിവി ഹിന്ദി',
    handle: '@whiteswantvhindi',
    url: 'https://www.facebook.com/profile.php?id=61580548986551',
    description: 'Hindi news coverage, national video bulletins, and interactive discussions',
    badge: 'HINDI',
    color: '#EA580C',
    icon: 'logo-facebook',
    image: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1532375810709-75b1da00537c?w=200&auto=format&fit=crop&q=80',
    tag: 'Hindi News',
  },
];

export const INSTAGRAM_PAGES = [
  {
    id: 'ig_whiteswantvnews',
    title: 'Whiteswan TV News Official',
    titleMl: 'വൈറ്റ്സ്വാൻ ടിവി ന്യൂസ് ഒഫീഷ്യൽ',
    handle: '@whiteswantvnews',
    url: 'https://www.instagram.com/whiteswantvnews/',
    description: 'Visual news reels, fast breaking alerts, stories and infographics on Instagram',
    badge: 'OFFICIAL',
    color: '#E1306C',
    icon: 'logo-instagram',
    image: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?w=600&auto=format&fit=crop&q=80',
    avatar: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=200&auto=format&fit=crop&q=80',
    tag: 'Official Page',
  },
];

export const LIVE_STREAM_URL = 'https://www.youtube.com/@whiteswantvonline/live';
