export const MARKETING_PACKAGES = [
  {
    id: 1,
    title: 'Poster Package + Social Media Push (Combo)',
    titleMl: 'പോസ്റ്റർ പാക്കേജ് + സോഷ്യൽ മീഡിയ പുഷ് (കോംബോ)',
    category: 'digital',
    categoryName: 'Digital Ads',
    categoryNameMl: 'ഡിജിറ്റൽ പരസ്യങ്ങൾ',
    price: 4000,
    priceFormatted: '₹4,000',
    duration: '1 Month',
    adType: 'Static Homepage Poster',
    description: 'Poster image displayed on homepage; ideal for local events, shop openings, and business announcements.',
    icon: 'image-outline',
    color: '#0284C7',
    popular: true,
  },
  {
    id: 2,
    title: 'Card Ads on News Cards',
    titleMl: 'വാർത്ത കാർഡുകളിൽ പരസ്യം',
    category: 'digital',
    categoryName: 'Digital Ads',
    categoryNameMl: 'ഡിജിറ്റൽ പരസ്യങ്ങൾ',
    price: 2000,
    priceFormatted: '₹2,000',
    duration: '1 Month',
    adType: 'Image Cards (Square / Portrait)',
    description: 'Shown between live and uploaded news posts for high visibility and instant reader engagement.',
    icon: 'newspaper-outline',
    color: '#2563EB',
    popular: false,
  },
  {
    id: 3,
    title: 'Cards on Wishes Page',
    titleMl: 'വിഷസ് പേജ് പരസ്യ കാർഡുകൾ',
    category: 'digital',
    categoryName: 'Digital Ads',
    categoryNameMl: 'ഡിജിറ്റൽ പരസ്യങ്ങൾ',
    price: 1000,
    priceFormatted: '₹1,000',
    duration: '1 Month',
    adType: 'Wishes Page Cards',
    description: 'Featured on Wishes Wall page with brand credits and social link.',
    icon: 'gift-outline',
    color: '#EC4899',
    popular: false,
  },
  {
    id: 4,
    title: 'Video Advertisements / Reels (Combo)',
    titleMl: 'വീഡിയോ പരസ്യങ്ങൾ / റീൽസ് (കോംബോ)',
    category: 'video',
    categoryName: 'Video & Reels',
    categoryNameMl: 'വീഡിയോ & റീൽസ്',
    price: 3000,
    priceFormatted: '₹3,000',
    duration: 'Per Upload',
    adType: 'Short Video Ads',
    description: 'Short video ads uploaded on YouTube Reels, Facebook Video and Instagram feed.',
    icon: 'videocam-outline',
    color: '#DC2626',
    popular: true,
  },
  {
    id: 5,
    title: 'Video Banner',
    titleMl: 'ഹോംപേജ് വീഡിയോ ബാനർ',
    category: 'video',
    categoryName: 'Video & Reels',
    categoryNameMl: 'വീഡിയോ & റീൽസ്',
    price: 2000,
    priceFormatted: '₹2,000',
    duration: '1 Month',
    adType: 'Homepage Video Banner',
    description: 'Mute autoplay video banner in the main homepage hero slider for maximum branding.',
    icon: 'play-circle-outline',
    color: '#7C3AED',
    popular: false,
  },
  {
    id: 6,
    title: 'Display Banner',
    titleMl: 'ഡിസ്പ്ലേ ബാനർ',
    category: 'digital',
    categoryName: 'Digital Ads',
    categoryNameMl: 'ഡിജിറ്റൽ പരസ്യങ്ങൾ',
    price: 1800,
    priceFormatted: '₹1,800',
    duration: '1 Month',
    adType: 'Sidebar / Footer Banner',
    description: 'Static banner on high-traffic article reader and content pages.',
    icon: 'browsers-outline',
    color: '#0D9488',
    popular: false,
  },
  {
    id: 7,
    title: 'Header / Sidebar Banners',
    titleMl: 'ടോപ്പ് ഹെഡർ / സൈഡ്‌ബാർ ബാനറുകൾ',
    category: 'digital',
    categoryName: 'Digital Ads',
    categoryNameMl: 'ഡിജിറ്റൽ പരസ്യങ്ങൾ',
    price: 2500,
    priceFormatted: '₹2,500',
    duration: '1 Month',
    adType: 'Rotating Top Banner (728x90 px)',
    description: 'Rotating premium banners placed prominently above the news section on all devices.',
    icon: 'options-outline',
    color: '#4F46E5',
    popular: false,
  },
  {
    id: 8,
    title: 'Sponsored Email Newsletter',
    titleMl: 'സ്പോൺസേർഡ് ഇമെയിൽ ന്യൂസ്‌ലെറ്റർ',
    category: 'content',
    categoryName: 'Content & PR',
    categoryNameMl: 'കണ്ടന്റ് & പി.ആർ',
    price: 1800,
    priceFormatted: '₹1,800',
    duration: '1 Edition',
    adType: 'Email Newsletter Banner',
    description: 'Exclusive advertisement banner sent directly to verified email subscribers.',
    icon: 'mail-outline',
    color: '#EA580C',
    popular: false,
  },
  {
    id: 9,
    title: 'Social Media Push',
    titleMl: 'സോഷ്യൽ മീഡിയ പ്രൊമോഷൻ',
    category: 'social',
    categoryName: 'Social Media',
    categoryNameMl: 'സോഷ്യൽ മീഡിയ',
    price: 1500,
    priceFormatted: '₹1,500',
    duration: '3 Posts',
    adType: 'Social Media Posts',
    description: 'FB + Instagram + YouTube posts boosted directly to target Kerala and NRI audience.',
    icon: 'share-social-outline',
    color: '#1877F2',
    popular: true,
  },
  {
    id: 10,
    title: 'Sponsored Podcast',
    titleMl: 'സ്പോൺസേർഡ് പോഡ്‌കാസ്റ്റ്',
    category: 'content',
    categoryName: 'Content & PR',
    categoryNameMl: 'കണ്ടന്റ് & പി.ആർ',
    price: 10000,
    priceFormatted: '₹10,000',
    duration: 'Per Episode',
    adType: 'Full Sponsor Slot',
    description: 'Dedicated intro and outro audio/video sponsor shoutouts and visual brand placement.',
    icon: 'mic-outline',
    color: '#9333EA',
    popular: false,
  },
  {
    id: 11,
    title: 'Soft Stories (PR Story)',
    titleMl: 'സോഫ്റ്റ് സ്റ്റോറികൾ (ബ്രാൻഡ് പി.ആർ)',
    category: 'content',
    categoryName: 'Content & PR',
    categoryNameMl: 'കണ്ടന്റ് & പി.ആർ',
    price: 10000,
    priceFormatted: '₹10,000',
    duration: 'Per Story',
    adType: 'PR / Human-Interest Story',
    description: 'PR / Human-Interest Story - In-depth brand storytelling article with social media boost.',
    icon: 'book-outline',
    color: '#16A34A',
    popular: false,
  },
  {
    id: 12,
    title: 'Native Advertisement + Soft Stories',
    titleMl: 'നേറ്റീവ് പരസ്യം + സോഫ്റ്റ് സ്റ്റോറികൾ',
    category: 'content',
    categoryName: 'Content & PR',
    categoryNameMl: 'കണ്ടന്റ് & പി.ആർ',
    price: 10000,
    priceFormatted: '₹10,000',
    duration: '1 Article',
    adType: 'Sponsored Editorial Article',
    description: 'Promotional article styled like mainstream news, tagged as Partnered Content.',
    icon: 'document-text-outline',
    color: '#0891B2',
    popular: true,
  },
  {
    id: 13,
    title: 'Branded Newsletter',
    titleMl: 'ബ്രാൻഡഡ് ന്യൂസ്‌ലെറ്റർ',
    category: 'content',
    categoryName: 'Content & PR',
    categoryNameMl: 'കണ്ടന്റ് & പി.ആർ',
    price: 1500,
    priceFormatted: '₹1,500',
    duration: '1 Edition',
    adType: 'Branded Newsletter',
    description: 'Presented by branding with one dedicated featured story.',
    icon: 'megaphone-outline',
    color: '#D97706',
    popular: false,
  },
  {
    id: 14,
    title: 'Featured / Mini Stories',
    titleMl: 'ഫീച്ചേർഡ് / മിനി സ്റ്റോറികൾ',
    category: 'content',
    categoryName: 'Content & PR',
    categoryNameMl: 'കണ്ടന്റ് & പി.ആർ',
    price: 5000,
    priceFormatted: '₹5,000',
    duration: 'Per Piece',
    adType: 'Featured Editorial + Photo',
    description: 'Short Editorial + Photo featured on Whiteswan TV format with social repost.',
    icon: 'star-outline',
    color: '#F59E0B',
    popular: false,
  },
  {
    id: 15,
    title: 'Prime Talk Show Package',
    titleMl: 'പ്രൈം ടോക്ക് ഷോ പാക്കേജ്',
    category: 'video',
    categoryName: 'Video & Reels',
    categoryNameMl: 'വീഡിയോ & റീൽസ്',
    price: 25000,
    priceFormatted: '₹25,000',
    duration: 'Per Episode',
    adType: 'Talk Show Sponsorship',
    description: 'Logo cup on table, logo on both hosts shirts, full episode exposure and high brand recall.',
    icon: 'tv-outline',
    color: '#BE123C',
    popular: true,
  },
];

export const MARKETING_CATEGORIES = [
  { key: 'all', label: 'All Packages', labelMl: 'എല്ലാം', icon: 'apps-outline' },
  { key: 'digital', label: 'Digital Ads', labelMl: 'ഡിജിറ്റൽ', icon: 'image-outline' },
  { key: 'video', label: 'Video & Reels', labelMl: 'വീഡിയോ', icon: 'videocam-outline' },
  { key: 'social', label: 'Social Media', labelMl: 'സോഷ്യൽ', icon: 'share-social-outline' },
  { key: 'content', label: 'Content & PR', labelMl: 'കണ്ടന്റ് / PR', icon: 'document-text-outline' },
];

export const WHATSAPP_CONTACT_NUMBER = '918891352542';
export const MARKETING_CONTACT_PHONE = '+919633052562';
